Add validations and unit tests
balatstar/blog pull request #3
Opened 2023-10-26 16:04 UTC by balatstar

The following were implemented in this branch:

Add validations for the User model:
- name must not be blank
- posts_counter must be an integer greater than or equal to zero

Add validations for the Post model:
- title must not be blank and not exceed 250 characters
- comments_counter must be an integer greater than or equal to zero
- likes_counter must be an integer greater than or equal to zero

Add unit tests for all models' methods and validations.

2023-10-26 16:42 UTC, mckent05 requested changes
Hi @balatstar, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- You have done well writing validations and specs for your models 👏 👏 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-26 16:42 UTC, mckent05 commented on spec/models/post_spec.rb
> +  end
- Good job done so far, but according to the project requirement, you are to test all customer methods in your model. Please write tests for the `increment_post_counter` and `decrement_post_counter`. Please fix this 🙏 
- Also, please write tests for the increment and decrement posts_comment_counter in the comment model, please fix this to ensure the methods in your models are tested according to the project requirements 😄 
- Also, please write tests for the increment and decrement likes_counter in the likes model, please fix this to ensure the methods in your models are tested according to the project requirements 😄

2023-10-27 06:40 UTC, balatstar commented
For the next code reviewer:

2023-10-27 07:25 UTC, DammyShittu approved these changes
Hi @balatstar,

## APPROVED 🟢

## Highlights
✔️ Passing tests

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-27 07:26 UTC, merged

2023-10-27 07:40 UTC, mckent05 commented
> For the next code reviewer: Hi! The previous reviewer asked me to add tests for increment and decrement posts counters but I already had it there (at the point where he added the comment). Please let me know if I'm not understanding correctly.
> 
> I've also added tests for incrementing and decrementing likes and comments, but if I misunderstood the one for posts they might be wrong, too. Thanks!

Hello @balatstar, Great work on your project so far. I saw that you tested to check if your `post_counter` increments or decrements upon creating or destroying a post respectively. But you did not exactly use the methods responsible for these actions upon creating and destroying. Instead of using the `reload` method after creating a post, I'd have expected that you called the function responsible for incrementing your post_counter, that way you can be sure the function works as expected. I hope I am clearer?

2023-10-27 07:59 UTC, balatstar commented
Hi @mckent05! Thanks for taking the time to reply! I already merged after the 2nd code reviewer's approval, but I appreciate your insight. Just a question, though... since I'm already automatically incrementing and decrementing post_counter whenever a post is created/destroyed, if I call the increment/decrement function again (instead of reload), won't this increment/decrement twice for each post created/destroyed (one automatically and the other one when I call the method again in the test)? Thanks!!

2023-10-27 15:45 UTC, mckent05 commented
> Hi @mckent05! Thanks for taking the time to reply! I already merged after the 2nd code reviewer's approval, but I appreciate your insight. Just a question, though... since I'm already automatically incrementing and decrementing post_counter whenever a post is created/destroyed, if I call the increment/decrement function again (instead of reload), won't this increment/decrement twice for each post created/destroyed (one automatically and the other one when I call the method again in the test)? Thanks!!

Hello @balatstar, sorry for the late response.Good question, In your models, the increment and decrement method are only called when the data is actually saved to the database, hence why we use the `after_save` module. But when in the test environment, the data is not saved into the database after it is created so the increment and decrement functions would not be triggered automatically. So when testing the functions would only be triggered when you call them. I hope this answers your question? :smile: